# Generated by extendr: do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_howfar_wrappers", use_symbols = TRUE, package_name = "howfar")

#' @docType package
#' @usage NULL
#' @useDynLib howfar, .registration = TRUE
NULL

rust_edt <- function(mask, nrows, ncols, n_cores) .Call(wrap__rust_edt, mask, nrows, ncols, n_cores)
