# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_howfar_wrappers", use_symbols = TRUE, package_name = "howfar")

#' @usage NULL
#' @useDynLib howfar, .registration = TRUE
NULL

#' Exact Euclidean distance transform of a binary mask.
#'
#' Returns the Euclidean distance (not squared) from each cell to the
#' nearest source cell, in cell units. R-callable entry point.
#'
#' @param mask Numeric vector, row-major, length nrows*ncols. Source cells
#'   have value > 0.5; background cells have value <= 0.5 (or NA, but the
#'   R wrapper should replace NAs first).
#' @param nrows Integer. Number of raster rows.
#' @param ncols Integer. Number of raster columns.
#' @param n_cores Integer. Number of threads to use. 0 means "use rayon's
#'   default" (all logical cores). Positive values cap parallelism at that
#'   thread count; 1 runs serially. Negative values are treated as 0.
#' @return Numeric vector of distances, row-major, same length as `mask`.
rust_edt <- function(mask, nrows, ncols, n_cores) .Call(wrap__rust_edt, mask, nrows, ncols, n_cores)

#' Exact Euclidean distance transform returning distance in **metres**.
#'
#' Finds, for each cell, the planar-Euclidean nearest source cell (via the
#' feature transform), then measures the metric distance between cell centres:
#' `haversine` when `lonlat` is true, otherwise `euclidean` scaled by
#' `m_per_unit` (metres per CRS linear unit). Cell centres are derived from the
#' grid geometry: cell `(r, c)` has centre `(xmin + (c + 0.5) * xres,
#' ymax - (r + 0.5) * yres)`. Cells with no source return infinity.
#'
#' @param mask Numeric vector, row-major, length nrows*ncols (>0.5 = source).
#' @param nrows Integer. Number of raster rows.
#' @param ncols Integer. Number of raster columns.
#' @param n_cores Integer. Threads to use; 0 = rayon default, 1 = serial.
#' @param xmin Double. Left edge (x) of the raster extent.
#' @param ymax Double. Top edge (y) of the raster extent.
#' @param xres Double. Cell size in x.
#' @param yres Double. Cell size in y.
#' @param lonlat Logical. If true, use Haversine (lon/lat in degrees).
#' @param m_per_unit Double. Metres per CRS linear unit (projected only).
#' @return Numeric vector of distances in metres, row-major.
rust_edt_meters <- function(mask, nrows, ncols, n_cores, xmin, ymax, xres, yres, lonlat, m_per_unit) .Call(wrap__rust_edt_meters, mask, nrows, ncols, n_cores, xmin, ymax, xres, yres, lonlat, m_per_unit)

#' Exact great-circle (Haversine) distance to the nearest source, in metres.
#'
#' Unlike the grid distance transform, this finds the source cell that is
#' genuinely nearest in great-circle distance — via a 3D nearest-neighbour
#' query over the source cells mapped onto the unit sphere — and returns the
#' Haversine distance to it. Correct at any latitude and across the
#' antimeridian; the only remaining approximation is the rasterisation of
#' features to cell centres.
#'
#' Cell centres are lon/lat (degrees) from the grid geometry, using the same
#' indexing convention as `rust_edt_meters`. Cells with no source return
#' infinity.
#'
#' @param mask Numeric vector, row-major, length nrows*ncols (>0.5 = source).
#' @param nrows Integer. Number of raster rows.
#' @param ncols Integer. Number of raster columns.
#' @param n_cores Integer. Threads to use; 0 = rayon default, 1 = serial.
#' @param xmin Double. Left edge (longitude) of the extent.
#' @param ymax Double. Top edge (latitude) of the extent.
#' @param xres Double. Cell size in longitude (degrees).
#' @param yres Double. Cell size in latitude (degrees).
#' @return Numeric vector of great-circle distances in metres, row-major.
rust_geo_distance <- function(mask, nrows, ncols, n_cores, xmin, ymax, xres, yres) .Call(wrap__rust_geo_distance, mask, nrows, ncols, n_cores, xmin, ymax, xres, yres)

